image: gcc:latest

stages:
  - build
  - test
  - clean

before_script:
  - apt-get update && apt-get install -y bats

build_job:
  stage: build
  script:
    - make build

test_job:
  stage: test
  script:
    - make test

clean_job:
  stage: clean
  script:
    - make clean