stages:
  - build
  - test

variables:
  bats: "bats/bats-core/bin/bats"
  CC: "gcc"
  CFLAGS: "-Wall -Wextra -std=c99"

before_script:
  - apt-get update && apt-get install -y gcc git make libcunit1 libcunit1-doc libcunit1-dev

build_job:
  stage: build
  script:
    - make build

test_job:
  stage: test
  script:
    - git submodule update --init --recursive
    - make test
  dependencies:
    - build_job

