image: gcc:latest

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y bats

build_job:
  stage: build
  script:
    - make build

test_job:
  stage: test
  script:
    - git submodule update --init --recursive
    - make test

